version: "3.9"

services:
  inquiry-postgres:
    container_name: portal-postgres
    image: docker.arvancloud.ir/postgres:latest
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'piana_portal_db'
    volumes:
      - 'portal-postgres-data:/var/lib/postgresql/data'
    ports:
      - '15433:5432'
    expose:
      - '15433'
    networks:
      portal-net:
        ipv4_address: 172.29.0.2

  portal-redis-master:
    image: docker.arvancloud.ir/redis:latest
    container_name: portal-redis-master
    hostname: redis-master
    ports:
      - "6379:6379"
    volumes:
      - ./data/master:/data
    command:
      [
        "redis-server",
        "--appendonly",
        "yes",
        "--repl-diskless-load",
        "on-empty-db",
        "--replica-announce-ip",
        "${HOST_IP}",
        "--replica-announce-port",
        "6379",
        "--protected-mode",
        "no"
      ]
    networks:
      portal-net:
        ipv4_address: 172.29.0.3

  portal-redis-slave-1:
    image: docker.arvancloud.ir/redis:latest
    container_name: portal-redis-slave-1
    hostname: redis-slave-1
    depends_on:
      - portal-redis-master
    ports:
      - "6380:6379"
    volumes:
      - ./data/slave1:/data
    command:
      [
        "redis-server",
        "--appendonly",
        "yes",
        "--replicaof",
        "portal-redis-master",
        "6379",
        "--repl-diskless-load",
        "on-empty-db",
        "--replica-announce-ip",
        "${HOST_IP}",
        "--replica-announce-port",
        "6380",
        "--protected-mode",
        "no"
      ]
    networks:
      portal-net:
        ipv4_address: 172.29.0.4


  portal-redis-slave-2:
    image: docker.arvancloud.ir/redis:latest
    container_name: portal-redis-slave-2
    hostname: redis-slave-2
    depends_on:
      - portal-redis-master
    ports:
      - "6381:6379"
    volumes:
      - ./data/slave2:/data
    command:
      [
        "redis-server",
        "--appendonly",
        "yes",
        "--replicaof",
        "portal-redis-master",
        "6379",
        "--repl-diskless-load",
        "on-empty-db",
        "--replica-announce-ip",
        "${HOST_IP}",
        "--replica-announce-port",
        "6381",
        "--protected-mode",
        "no"
      ]
    networks:
      portal-net:
        ipv4_address: 172.29.0.5

  portal-sentinel-1:
    image: docker.arvancloud.ir/redis:latest
    container_name: portal-sentinel-1
    hostname: sentinel-1
    depends_on:
      - portal-redis-master
    ports:
      - "26379:26379"
    command: >
      sh -c 'echo "bind 0.0.0.0" > /etc/sentinel.conf &&
            echo "sentinel monitor portal-redis-master ${HOST_IP} 6379 2" >> /etc/sentinel.conf &&
            echo "sentinel resolve-hostnames yes" >> /etc/sentinel.conf &&
            echo "sentinel down-after-milliseconds portal-redis-master 10000" >> /etc/sentinel.conf &&
            echo "sentinel failover-timeout portal-redis-master 10000" >> /etc/sentinel.conf &&
            echo "sentinel parallel-syncs portal-redis-master 1" >> /etc/sentinel.conf &&
            redis-sentinel /etc/sentinel.conf'
    networks:
      portal-net:
        ipv4_address: 172.29.0.6

  portal-sentinel-2:
    image: docker.arvancloud.ir/redis:latest
    container_name: portal-sentinel-2
    hostname: sentinel-2
    depends_on:
      - portal-redis-master
    ports:
      - "26380:26379"
    command: >
      sh -c 'echo "bind 0.0.0.0" > /etc/sentinel.conf &&
            echo "sentinel monitor portal-redis-master ${HOST_IP} 6379 2" >> /etc/sentinel.conf &&
            echo "sentinel resolve-hostnames yes" >> /etc/sentinel.conf &&
            echo "sentinel down-after-milliseconds portal-redis-master 10000" >> /etc/sentinel.conf &&
            echo "sentinel failover-timeout portal-redis-master 10000" >> /etc/sentinel.conf &&
            echo "sentinel parallel-syncs portal-redis-master 1" >> /etc/sentinel.conf &&
            redis-sentinel /etc/sentinel.conf'
    networks:
      portal-net:
        ipv4_address: 172.29.0.7

  portal-sentinel-3:
    image: docker.arvancloud.ir/redis:latest
    container_name: portal-sentinel-3
    hostname: sentinel-3
    depends_on:
      - portal-redis-master
    ports:
      - "26381:26379"
    command: >
      sh -c 'echo "bind 0.0.0.0" > /etc/sentinel.conf &&
            echo "sentinel monitor portal-redis-master ${HOST_IP} 6379 2" >> /etc/sentinel.conf &&
            echo "sentinel resolve-hostnames yes" >> /etc/sentinel.conf &&
            echo "sentinel down-after-milliseconds portal-redis-master 10000" >> /etc/sentinel.conf &&
            echo "sentinel failover-timeout portal-redis-master 10000" >> /etc/sentinel.conf &&
            echo "sentinel parallel-syncs portal-redis-master 1" >> /etc/sentinel.conf &&
            redis-sentinel /etc/sentinel.conf'
    networks:
      portal-net:
        ipv4_address: 172.29.0.8


  portal-redisinsight:
    image: docker.arvancloud.ir/redis/redisinsight:latest
    container_name: portal-redisinsight
    ports:
      - "5540:5540"
    networks:
      portal-net:
        ipv4_address: 172.29.0.9

volumes:
  portal-postgres-data:

networks:
  portal-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16